SEED: 0
SAVE_CHECKPOINT: false #true
DATASET:
  CACHE: False
  ENABLE_OUT_RANGE_TRAJ: True
  TYPE: WaymoOpenMotion
  MAX_TIME_STEP: 50
  TIME_SAMPLE_GAP: 1
  AUGMENTATION:
    ENABLE: true
    RANDOM_MASK_RATE: 0.1
  TRAJ_TYPE: xy_theta_relative
  DATA_LIST:
    TEST: val.txt
    VAL: val.txt
    TRAIN: train.txt
  TEXT:
    TYPE: attr_ind
    ALL_CLASSES:
    - 'pos'
    - 'distance'
    - 'direction'
    - 'speed'
    - 'action'
    - 'type_traj'
    CLASS:
    - 'pos'
    - 'distance'
    - 'direction'
    - 'speed'
    - 'action'
    NEGATIVE_SAMPLE_NUM: 10
    COUNT_BASE: 1
    DISTANCE_BASE: 10
    SPEED_BASE: 2.5
    USE_PADDING: True
    PADDING: -1
    FLATTEN: False
    USE_TRAJ: True
    ACTION_STEP: 4
    MAX_TIME: 40
    CLUSTER_DIM: 5
    CLUSTER_NUM: 5


DEBUG: False
EXPERIMENT_DIR: InteractTraj
EXPERIMENT_NAME: train

LOSS:
  DETR:
    AE_MODES: ['text']
    MATCH_METHOD: sequential
    PRED_BACKGROUND: False
    ALIGNMENT:
      ENABLE: false
    LOSSES:
      - labels
      - attributes
    MATCH_COST:
      CLASS: 1.0
    TEXT_AE: true
    WEIGHT:
      labels: 1.0
      attributes: 1.0
    ATTR_WEIGHT:
      speed: 1.5
      pos: 2.0
      vel_heading: 1.0
      heading: 1.0
      bbox: 2.0
      motion: 1.0

MAX_EPOCHES: 100
METRIC:
  TYPE:
  - MMD
  - traj_match

MODEL:
  TYPE: InteractTraj

  MOTION:
    ENABLE: true
    STEP: 49
    CUMSUM: true
    PRED_MODE: mlp_gmm
    CLS_WEIGHT: 0.1
    K: 6
    PRED_HEADING_VEL: true

  PREDICT_EGO: true
  SCENE:
    EMBEDDING_DIM: 256
    HIDDEN_DIMS: []
    INIT_CFG:
      hidden_dim: 256
      DECODER:
        DROPOUT: 0.1
        FF_DIM: 2048
        LANE_NUM: 384
        MAP_POS: none
        MLP_DIM: 512
        NHEAD: 4
        NLAYER: 1
        QUERY_NUM: 32
        TYPE: agent_decode
        ATTR_GMM_ENABLE: True
        ATTR_GMM_K: 5
  
      ATTR_QUERY:
        POS_ENCODING_DIM: 252
        
  HETERO_CFG:
    edge_dim: 10    
    hidden_dim: 512
    num_heads: 8
    out_dim: 512
    num_layers: 2
    feats_drop_rate: 0.1
    slope: 0.02
    beta: 0
   
  HDGT_CFG:
    num_of_gnn_layer: 6
    hidden_dim: 256
    num_prediction: 6
    head_dim: 32
    dropout: 0.0
    refine_num: 5
    output_vel: true
    cumsum_vel: true    



LOAD_CHECKPOINT_MODEL: false
LOAD_CHECKPOINT_PATH: #/home/ubuntu/DATA2/nuplan/results/lctgen/train/lctgen_attr_ind_motion/5fv1o13a/checkpoints/last.ckpt
LOAD_CHECKPOINT_TRAINER: false

TEST:
  BATCH_SIZE: 32
  SHUFFLE: false
  NUM_WORKERS: 4
TRAIN:
  BATCH_SIZE: 16
  LR: 0.00003
  SHUFFLE: false
  OPTIMIZER: AdamW
  SCHEDULER:
    MILESTONES:
    - 10
    - 20
    - 40
    - 70
    - 90
  NUM_WORKERS: 4
VAL:
  BATCH_SIZE: 32
  SHUFFLE: false
  NUM_WORKERS: 4
VAL_INTERVAL: 10
VIS_INTERVAL: 10
WANDB_PROJ: train
